import type { Lesson } from '@/domains/lesson';

function mkFlat(s: Lesson['sessions']): Lesson['blocks'] {
  return (s ?? []).flatMap((x) => x.blocks);
}

// PRD §14 + Curriculum §9 — Neovim 9 lecciones, modelo verbo+objeto
// Cada lección: recall → concept → isolation → pattern → combination → challenge → evaluation
export const NEOVIM_ES: Lesson[] = [
  {
    id: 'neovim-es-01',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '01 — Normal e Insert',
    description: 'El teclado cambia de función según el modo. i/a, Esc, I/A.',
    objectives: ['Distinguir NORMAL vs INSERT', 'i/a/I/A + Esc'],
    prerequisites: ['typing-es-03'],
    skills: ['vim-modes'],
    targetKeys: ['KeyI', 'KeyA', 'Escape'],
    sessions: [
      {
        id: 'neovim-es-01--A',
        title: 'Session A — Discover',
        objectives: ['Entender modos'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v01-A1', type: 'concept', title: 'Concept — modos', instructions: 'Vim no escribe directo: Normal mueves/edias, Insert escribes. i=insertar donde estás, a=añadir después, I=inicio línea, A=final línea, Esc=volver Normal.', targetKeys: ['KeyI', 'KeyA'], content: ['NORMAL ↔ INSERT'], difficulty: 1 },
          { id: 'v01-A2', type: 'recall', title: 'Recall — from typing', instructions: 'Recupera fj dk alternancia para calentar dedos', targetKeys: ['KeyF', 'KeyJ'], content: ['fj dk sl añ'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-01--B',
        title: 'Session B — Isolation',
        objectives: ['Transición modo sin error'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v01-B1', type: 'isolation', title: 'Lab 1 — i', instructions: 'Insertar antes del cursor: posición y presiona i, escribe hola, Esc', targetKeys: ['KeyI'], content: ['i hola Esc'], difficulty: 1 },
          { id: 'v01-B2', type: 'isolation', title: 'Lab 2 — a', targetKeys: ['KeyA'], content: ['a mundo Esc'], difficulty: 1 },
          { id: 'v01-B3', type: 'pattern', title: 'Lab 3/4 — I/A + Esc', targetKeys: ['KeyI', 'KeyA'], content: ['I inicio Esc', 'A final Esc'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-01--C',
        title: 'Session C — Combination & Challenge',
        objectives: ['Modificar frase con mínimo cambio de modo'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v01-C1', type: 'combination', targetKeys: ['KeyI', 'KeyA'], content: ['i a Esc'], difficulty: 2 },
          { id: 'v01-C2', type: 'challenge', title: 'Challenge — mínimo modo', instructions: 'Convierte [hola] en [hola mundo] yendo al final con $ , a , " mundo", Esc — cuenta cambios de modo', targetKeys: ['KeyA'], content: ['hola mundo'], difficulty: 3 },
          { id: 'v01-C3', type: 'evaluation', title: 'Evaluation', targetKeys: ['KeyI', 'KeyA'], content: ['hola mundo'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim', referenceKeystrokes: 8 },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-02',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '02 — Movimiento h/j/k/l',
    description: 'Maze del cursor. Sin flechas — NV004.',
    objectives: ['h← j↓ k↑ l→', 'Diagonal y texto real'],
    prerequisites: ['neovim-es-01'],
    skills: ['vim-motions'],
    targetKeys: ['KeyH', 'KeyJ', 'KeyK', 'KeyL'],
    sessions: [
      {
        id: 'neovim-es-02--A',
        title: 'Session A — Discover',
        objectives: ['Mnemotecnia h-left, l-right, j down hook, k up'],
        estimatedMinutes: 5,
        blocks: [
          { id: 'v02-A1', type: 'concept', instructions: 'h izquierda, l derecha, j abajo gancho, k arriba.', targetKeys: ['KeyH', 'KeyJ', 'KeyK', 'KeyL'], content: ['h j k l'], difficulty: 1 },
          { id: 'v02-A2', type: 'recall', instructions: 'Recupera i/a Esc rápido', targetKeys: ['KeyI', 'KeyA'], content: ['i a Esc'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-02--B',
        title: 'Session B — Maze',
        objectives: ['Horizontal → vertical → diagonal → obstáculos'],
        estimatedMinutes: 10,
        blocks: [
          { id: 'v02-B1', type: 'isolation', title: 'Horizontal', targetKeys: ['KeyH', 'KeyL'], content: ['h h h', 'l l l'], difficulty: 1 },
          { id: 'v02-B2', type: 'pattern', title: 'Vertical + diagonal', targetKeys: ['KeyJ', 'KeyK'], content: ['j j', 'k k', 'l l l j'], difficulty: 2 },
          { id: 'v02-B3', type: 'combination', title: 'Obstáculos + texto real', targetKeys: ['KeyH', 'KeyJ', 'KeyK', 'KeyL'], content: ['l l l j', 'h j k l'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-02--C',
        title: 'Session C — Challenge & Evaluation',
        objectives: ['Navegar archivo sin flechas'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v02-C1', type: 'challenge', title: 'Challenge — sin flechas', instructions: 'En "hola mundo feliz" llega a la f de feliz solo con l/w — flechas bloqueadas', targetKeys: ['KeyL'], content: ['feliz'], difficulty: 3 },
          { id: 'v02-C2', type: 'evaluation', targetKeys: ['KeyH', 'KeyJ', 'KeyK', 'KeyL'], content: ['l l l j'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim', referenceKeystrokes: 4, allowArrows: false },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-03',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '03 — Palabras w/b/e',
    description: 'Movimiento por significado textual, no caracteres. Introduce operador dw.',
    objectives: ['w next word, b back, e end', 'dw como primer verbo+objeto'],
    prerequisites: ['neovim-es-02'],
    skills: ['vim-words'],
    targetKeys: ['KeyW', 'KeyB', 'KeyE', 'KeyD'],
    sessions: [
      {
        id: 'neovim-es-03--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar h/j/k/l sin flechas', 'Entender palabra como unidad'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v03-A0', type: 'recall', title: 'Recall — h/j/k/l + i/a', instructions: 'Recuperación activa: sin mostrar, ¿qué hace j? ¿Esc?', targetKeys: ['KeyH', 'KeyJ', 'KeyK', 'KeyL', 'KeyI'], content: ['h j k l', 'i a Esc'], difficulty: 2 },
          { id: 'v03-A1', type: 'concept', instructions: 'En "hola mundo feliz": w→siguiente palabra inicio, b←atrás, e→fin palabra. Más rápido que llll.', targetKeys: ['KeyW', 'KeyB', 'KeyE'], content: ['w b e'], difficulty: 1 },
        ],
      },
      {
        id: 'neovim-es-03--B',
        title: 'Session B — Drills',
        objectives: ['w w w, b b, e'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v03-B1', type: 'pattern', targetKeys: ['KeyW', 'KeyB', 'KeyE'], content: ['w w w', 'b b', 'e'], difficulty: 2 },
          { id: 'v03-B2', type: 'pattern', targetKeys: ['KeyW', 'KeyB', 'KeyE'], content: ['w w b e'], difficulty: 2 },
          { id: 'v03-B3', type: 'concept', title: 'Primer operador d+w', instructions: 'Fórmula: operador + movimiento → dw borra palabra', targetKeys: ['KeyD', 'KeyW'], content: ['dw'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-03--C',
        title: 'Session C — Challenge & Evaluation',
        objectives: ['Eliminar palabras'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v03-C1', type: 'challenge', instructions: 'Borra 1 palabra / 2 palabras / hasta determinada palabra sin decir comando', targetKeys: ['KeyD', 'KeyW'], content: ['dw'], difficulty: 3 },
          { id: 'v03-C2', type: 'evaluation', targetKeys: ['KeyW', 'KeyB', 'KeyE', 'KeyD'], content: ['dw'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim', referenceKeystrokes: 2 },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-04',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '04 — Líneas 0 ^ $',
    description: 'Inicio y fin de línea. Combinaciones d$, c$, y$.',
    objectives: ['0 inicio absoluto, ^=primer no-espacio, $=fin', 'd$ c$ y$'],
    prerequisites: ['neovim-es-03'],
    skills: ['vim-lines'],
    targetKeys: ['Digit0', 'Equal'],
    sessions: [
      {
        id: 'neovim-es-04--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar w/b/e + dw', 'Indentación'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v04-A0', type: 'recall', instructions: 'Recupera: w/b/e y dw sin pista', targetKeys: ['KeyW', 'KeyB', 'KeyE', 'KeyD'], content: ['w b e', 'dw'], difficulty: 2 },
          { id: 'v04-A1', type: 'concept', instructions: 'Línea "   hola": 0→primer espacio, ^→h, $→final.', targetKeys: ['Digit0', 'Equal'], content: ['0 ^ $'], difficulty: 1 },
          { id: 'v04-A2', type: 'pattern', targetKeys: ['Digit0', 'Equal'], content: ['$ 0 ^'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-04--B',
        title: 'Session B — Combinations',
        objectives: ['d$ c$ y$'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v04-B1', type: 'pattern', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['d$', 'c$', 'y$'], difficulty: 2 },
          { id: 'v04-B2', type: 'application', instructions: 'Editar server_name example.com; moviéndose inicio↔fin', targetKeys: ['Digit0', 'Equal', 'KeyD'], content: ['server_name example.com;'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-04--C',
        title: 'Session C — Challenge & Evaluation',
        estimatedMinutes: 6,
        blocks: [
          { id: 'v04-C1', type: 'challenge', instructions: 'Desde medio ve a fin con $ y añade "!" con a', targetKeys: ['Equal', 'KeyA'], content: ['!'], difficulty: 3 },
          { id: 'v04-C2', type: 'evaluation', targetKeys: ['Digit0', 'Equal'], content: ['!'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-05',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '05 — Documento gg G { }',
    description: 'Archivo y párrafo. 5G = línea 5.',
    objectives: ['gg inicio, G final, {/} párrafos, Ctrl-d/u'],
    prerequisites: ['neovim-es-04'],
    skills: ['vim-document'],
    targetKeys: ['KeyG'],
    sessions: [
      {
        id: 'neovim-es-05--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar 0 ^ $', 'Documento'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v05-A0', type: 'recall', instructions: 'Recupera 0 ^ $ y d$ sin pista', targetKeys: ['Digit0', 'Equal', 'KeyD'], content: ['0 ^ $', 'd$'], difficulty: 2 },
          { id: 'v05-A1', type: 'concept', instructions: 'Fichero largo: gg arriba, G abajo, { } párrafos, Ctrl-d/u media página.', targetKeys: ['KeyG'], content: ['gg G { }'], difficulty: 1 },
        ],
      },
      {
        id: 'neovim-es-05--B',
        title: 'Session B — Labs',
        objectives: ['Navegar README/config/source/logs sin scroll'],
        estimatedMinutes: 8,
        blocks: [
          { id: 'v05-B1', type: 'challenge', instructions: 'Con 3 líneas realiza gg → G → { sin scroll', targetKeys: ['KeyG'], content: ['gg G'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-05--C',
        title: 'Session C — Evaluation',
        estimatedMinutes: 5,
        blocks: [
          { id: 'v05-C1', type: 'evaluation', targetKeys: ['KeyG'], content: ['gg G'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-06',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '06 — Edición x r u Ctrl-r',
    description: 'Corregir errores tipográficos sin Insert innecesario.',
    objectives: ['x borrar char, r reemplazar, u deshacer, Ctrl-r rehacer'],
    prerequisites: ['neovim-es-05'],
    skills: ['vim-edit'],
    targetKeys: ['KeyX', 'KeyR'],
    sessions: [
      {
        id: 'neovim-es-06--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar gg G { }', 'Edición char'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v06-A0', type: 'recall', instructions: 'Recupera gg G { } sin pista', targetKeys: ['KeyG'], content: ['gg G', '{ }'], difficulty: 2 },
          { id: 'v06-A1', type: 'concept', instructions: 'x=Delete bajo cursor (hoxa→hola). r=reemplaza sin Insert (r a). u=undo, Ctrl-r=redo.', targetKeys: ['KeyX', 'KeyR'], content: ['x r u'], difficulty: 1 },
        ],
      },
      {
        id: 'neovim-es-06--B',
        title: 'Session B — Labs',
        estimatedMinutes: 8,
        blocks: [
          { id: 'v06-B1', type: 'challenge', title: 'Reto dokcer→docker', instructions: 'En "hoxa" mueve a x y r l → "hola"', targetKeys: ['KeyR', 'KeyX'], content: ['r'], difficulty: 3 },
          { id: 'v06-B2', type: 'challenge', title: 'Debug — 10 errores sin Insert', instructions: 'Corrige 10 typos solo con x/r', targetKeys: ['KeyX', 'KeyR'], content: ['dokcer'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-06--C',
        title: 'Session C — Evaluation',
        estimatedMinutes: 5,
        blocks: [
          { id: 'v06-C1', type: 'evaluation', targetKeys: ['KeyX', 'KeyR'], content: ['r'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-07',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '07 — Operators d/c/y + text objects',
    description: 'Lección central: operador+movimiento/objeto. iw aw ciw diw yiw.',
    objectives: ['d c y + w e $ 0', 'iw aw ciw diw'],
    prerequisites: ['neovim-es-06'],
    skills: ['vim-operators'],
    targetKeys: ['KeyD', 'KeyC', 'KeyY'],
    sessions: [
      {
        id: 'neovim-es-07--A',
        title: 'Session A — Recall + Discover (modelo verbo+objeto)',
        objectives: ['Recuperar x r u', 'Verbo+objeto'],
        estimatedMinutes: 7,
        blocks: [
          { id: 'v07-A0', type: 'recall', instructions: 'Recupera x r u sin pista', targetKeys: ['KeyX', 'KeyR'], content: ['x r', 'u'], difficulty: 2 },
          { id: 'v07-A1', type: 'concept', instructions: 'OPERADOR + MOVIMIENTO/OBJETO: dw de d$ cw c$ yw y$ · text objects: iw inner word, aw a word, ciw change inner word.', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['dw ciw'], difficulty: 1 },
          { id: 'v07-A2', type: 'pattern', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['dw', 'de', 'd$', 'cw', 'c$', 'yw', 'y$'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-07--B',
        title: 'Session B — Text objects',
        estimatedMinutes: 8,
        blocks: [
          { id: 'v07-B1', type: 'pattern', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['iw', 'aw', 'ciw', 'diw', 'yiw'], difficulty: 2 },
          { id: 'v07-B2', type: 'combination', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['dw ciw', 'diw yiw'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-07--C',
        title: 'Session C — Challenge generator & Evaluation',
        estimatedMinutes: 8,
        blocks: [
          { id: 'v07-C1', type: 'challenge', title: 'Generador: elimina/cambia/copia sin decir comando', instructions: 'Objetivo textual sin revelar comando — decide operador.', targetKeys: ['KeyD', 'KeyC'], content: ['vim'], difficulty: 3 },
          { id: 'v07-C2', type: 'evaluation', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['vim'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-08',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '08 — Líneas dd yy p + counts',
    description: 'COUNT + ACTION. Reorganizar archivo.',
    objectives: ['dd corta, yy copia, p/P pega', '2w 3j 5dd 2yy'],
    prerequisites: ['neovim-es-07'],
    skills: ['vim-lines-copy'],
    targetKeys: ['KeyD', 'KeyY', 'KeyP'],
    sessions: [
      {
        id: 'neovim-es-08--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar d/c/y + iw', 'COUNT+ACTION'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v08-A0', type: 'recall', instructions: 'Recupera dw ciw yiw sin pista', targetKeys: ['KeyD', 'KeyC', 'KeyY'], content: ['dw', 'ciw', 'yiw'], difficulty: 2 },
          { id: 'v08-A1', type: 'concept', instructions: 'dd línea entera, yy copia, p después, P antes. COUNT: 2w 3j 5dd 2yy.', targetKeys: ['KeyD', 'KeyY', 'KeyP'], content: ['dd yy p P'], difficulty: 1 },
          { id: 'v08-A2', type: 'pattern', targetKeys: ['KeyD', 'KeyY', 'KeyP'], content: ['2w', '3j', '5dd', '2yy'], difficulty: 2 },
        ],
      },
      {
        id: 'neovim-es-08--B',
        title: 'Session B — Lab reorganizar',
        estimatedMinutes: 8,
        blocks: [
          { id: 'v08-B1', type: 'challenge', instructions: 'Líneas A B C D → orden objetivo: dd → G → p', targetKeys: ['KeyD', 'KeyP'], content: ['dd p'], difficulty: 3 },
          { id: 'v08-B2', type: 'evaluation', targetKeys: ['KeyD', 'KeyY', 'KeyP'], content: ['dd p'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
  {
    id: 'neovim-es-09',
    courseId: 'neovim',
    version: 3,
    domain: 'neovim',
    title: '09 — Search / . u y repeat',
    description: 'Búsqueda y repetición — corazón de eficiencia. localhost→10.10.0.130',
    objectives: ['/ ? n N . * #', 'localhost→IP en múltiples sitios'],
    prerequisites: ['neovim-es-08'],
    skills: ['vim-search'],
    targetKeys: ['Slash'],
    sessions: [
      {
        id: 'neovim-es-09--A',
        title: 'Session A — Recall + Discover',
        objectives: ['Recuperar dd yy p + counts', 'Search'],
        estimatedMinutes: 6,
        blocks: [
          { id: 'v09-A0', type: 'recall', instructions: 'Recupera dd yy p 2w sin pista', targetKeys: ['KeyD', 'KeyY', 'KeyP'], content: ['dd', 'yy', 'p', '2w'], difficulty: 2 },
          { id: 'v09-A1', type: 'concept', instructions: '/hola + n/N, . repite última, * busca palabra bajo cursor, # atrás, u undo.', targetKeys: ['Slash'], content: ['/ n N . * #'], difficulty: 1 },
        ],
      },
      {
        id: 'neovim-es-09--B',
        title: 'Session B — Core challenge',
        estimatedMinutes: 10,
        blocks: [
          { id: 'v09-B1', type: 'application', title: 'Servidores → IP', instructions: 'server=localhost (x3) → 10.10.0.130 vía /localhost ciw 10.10.0.130 Esc n . n .', targetKeys: ['Slash'], content: ['/ dw . u'], difficulty: 3 },
          { id: 'v09-B2', type: 'challenge', instructions: 'Busca /mundo → dw → . → u sin decir comandos', targetKeys: ['Slash'], content: ['/ dw . u'], difficulty: 3 },
        ],
      },
      {
        id: 'neovim-es-09--C',
        title: 'Session C — Final Evaluation (archivo real)',
        estimatedMinutes: 10,
        blocks: [
          { id: 'v09-C1', type: 'evaluation', title: 'Evaluación final — objetivos sin comandos', instructions: 'Archivo con errores/líneas duplicadas/bloques desordenados. Solo objetivos.', targetKeys: ['Slash'], content: ['/ dw . u'], difficulty: 5 },
        ],
      },
    ],
    get blocks(): Lesson['blocks'] { return mkFlat(this.sessions); },
    set blocks(v: Lesson['blocks']) { void v; },
    evaluator: { kind: 'vim' },
    mastery: { minAccuracy: 0.9, consecutivePasses: 2 },
  },
];
export const getNeovimLesson = (id: string) => NEOVIM_ES.find((l) => l.id === id);
